# 4. 예외를 이용하지 않은 오류 처리 

> 예외(exception)를 던지는 것이 하나의 부수효과임을 간단히 언급하였다. 그렇다면 예외를 사용하지 않는다면 그 대신 무엇을 사용할까?
>
> > 핵심은, 실패 상황과 예외를 보통의 값으로 표현할 수 있으며, 일반적인 오류 처리-복구 패턴을 추상화한 고차 함수를 작성할 수 있다는 것이다. 오류를 값으로서 돌려준다는 함수적 해법은 더 안전하고 참조 투명성을 유지한다는 장점이 있다. 게다가 고차 함수 덕분에 예외의 주된 이점인 **오류 처리 논리의 통합(consolidation of error-handling logic)** 도 유지 된다. 



#### 4.1 예외의 장단점

> 예외가 왜 참조 투명성을 해칠까? 그리고 그것이 왜 문제가 될까?



###### 4.1 예외를 던지고 받기 

```scala
def failingFn(i: Int): Int = {
    val y : Int = throw new Exception("fail")
    // val y : Int = ...는 변수 y의 형식이 Int 이고 그 값은 = 의 우변과 같음을 선언
    try{
        val x = 42 + 5
        x + y
    }
    catch { case e : Exception => 43 }
    // catch블록은 이전 장에서 본 패턴 부합 블록과 다를 바 없다. case e : Exception 은 임의의
    // Exception과 부합하는 패턴으로, 부합하는 경우 그 Exception을 식별자 e에 묶는다. 
  	// 부합은 값 43을 돌려준다.
}

//결과 
-> failingFn(12)
-> java.lang.Exception : fail!
...
```

- 위 식을 보면, y 가 참조에 투명하지 않음을 증명할 수 있다.
- 임의의 참조 투명 표현식을 그것이 지칭하는 값으로 치환해도 프로그램의 의미가 변하지 않는것을 확인하면 된다. 

```scala
def failingFn2(i: Int): Int = {
    try{
        val x = 42 + 5
        x + ((throw new Exception("fail")) : Int)
        //던질 Exception에 그 어떤 형식이라도 지정할 수 있다. 여기서는 Int를 지정했다.
    }
    catch { case e : Exception => 43 }
}
//결과 
-> failingFn2(12)
-> 43
```

-  참조에 투명한 표현식의 의미
  - **문맥(context)에 의존하지 않으며** 지역적으로 추론할 수 있다.
- 참조에 투명하지 않은 표현식의 의미
  - **문맥에 의존적이고** 좀 더 전역의 추론이 필요하다.

```42 + 5```는 항상 47이지만, ``` throw new Exeption("fail")``` 은 문맥에 크게 의존한다. 

try 블록에 포함 여부에 따라 결과가 달라진다.



**예외의 주된 문제점 2가지**  		

- > **예외는 참조 투명성을 위반하고 문맥 의존성을 도입한다.**  
  >
  > 치환모형의 간단한 추론이 불가능해지고, 예외에 기초한 혼란스러운 코드가 만들어진다.  

- > **예외는 형식에 안전하지 않다.**
  >
  > failingFn의 형식인  Int => Int 만 보고는 이 함수가 예외를 던질 수 있다는 사실을 전혀 알 수 없다.  그래서 컴파일러는 호출자에게 그 예외들을 처리하는 방식을 강제 할 수 없다. 



**대안기법**

- "예외를 던지는 대신, 예외적인 조건이 발생했음을 뜻하는 값을 돌려준다. "
- '미리 정의 해 둘 수 있는 값들'을 대표하는 새로운 일반적 형식을 도입하고, 오류의 처리와 전파에 관한 공통적인 패턴들을 고차 함수들을 이용해서 캡슐화 한다. 
- **형식에 완전히 안전하며**, 컴파일러의 도움을 받아 실수를 미리 발견할 수 있다.



> **점검된 예외** 
>
> > Java의 점검된 예외 (checked exception) 는 적어도 오류를 처리할 것인지 다시 발생시킬 것인지의 결정을 강제하나, 결과적으로 호출하는 쪽에 판에 박힌코드 (boilerplate) 가 추가된다. 
> >
> > 중요한 점은, 점검된 예외는 **고차함수에는 통하지 않는다** 는 점이다. 고차 함수에서는 인수가 구체적으로 어떤 예외를 던질지 미리 알 수 없기 때문이다 
> >
> > ``` def map[A,B](l: List[A])(f:A=>B):List[B]```  이 함수는 점검된 예외와 잘 맞지 않는다. 
> >
> > 모든 가능한(f가 던질 수 있는) 점검된 예외마다 map의 개별적인 버전을 만들 수는 없는 일이다.  그렇게 하기로 했다고 해도, 어떤 예외가 가능한지 map이 알 수 있게 할 방법이 없다. 이는 Java에서도 일반적 코드가 RuntimeException이나 공통의 점검된 Exception 형식에 의존할 수밖에 없는 이유이다. 



#### 4.2 예외의 가능한 대안들

```scala
def mean(xs: Seq[Dobule]): Double = {
    if(xs.isEmpty){
        throw new ArithmeticException("mean of empty list")
    }
    else xs.sum/xs.length
}
```

- mean 함수는 소위 **부분함수(partial function)** 의 예이다. 부분함수란  일부 입력에 대해서는 정의되지 않는 함수이다. 
- 부분함수란
  - 일부 입력에 대해서는 정의되지 않는 함수 
  - 자신이 받아들이는 입력에 대해 입력 형식만으로는 결정되지 않는 , 어떤 가정을 두는 함수
  - 일부 x 에 대해서만 y인 함수 (제한을 둔 함수)



그럼 이런 mean 에 대해 예외 대신 사용할 수 있는 대안 몇가지는?

- **Double 형식의 가짜 값을 돌려주는 것이다.** 
  모든 경우에는 그냥 ```xs.sum/xs.length``` 를 돌려주고, 빈목록에 대해서는 0.0/0.0 (Double.NaN)을 돌려주는 것이다.
  이런 부류의 접근 방식은 예외 기능이 없는 언어에서 오류 처리하는데 흔히 쓰인다. 하지만 이런 방식은 좋지 않다. 
  그 이유는..
  - 오류가 소리 없이 전파될 수 있다. 호출자가 이런 오류 조건의 점검을 빼먹어도 컴파일러가 경고해 주지 않으며, 이후 코드가 제대로 작동하지 않을 수 있다. 그에 따라 오류가 훨씬 나중에 검출 되는 경우가 발생한다. 
  - 호출하는 쪽에 호출자가 '진짜' 결과를 받았는지 점검하는 명시적 ```if``` 문들로 구성된 판에 박힌 코드가 늘어 난다. 
  - 다형적 코드에서는 적용할 수 없다. 출력형식이 무엇이냐에 따라 결과가 각각 달라야 하는데 그럴 수 없다.
  - 호출자에게 특별한 방침이나 호출 규약을 요구한다. 호출자가 그냥 mean을 호출해서 그 결과를 사용하는 것 이상의 작업을 수행해야 한다. 

```scala
def mean_1(xs: IndexedSeq[Double], onEmpty: Double): Double = {
    if(xs.isEmpty) onEmpty
    else xs.sum/xs.length
}
```

- **함수가 무엇을 해야 하는지 말해주는 인수를 호출자가 지정해 주는 것이다.**

  이렇게 하면 **완전함수(total fucntion)** 가 되지만 문제는..

  - 결과가 정의되지 않는 경우의 처리 방식을 함수의 직접적인 호출자가 알고 있어야 한다는 점과 , 항상 Double 형식으로 값을 돌려주어야 한다는 단점이 존재 한다. 
  - 이렇게 할경우 유연성을 얻을 수 없게 된다. 



#### 4.3 Option 자료형식

> 함수가 항상 답을 내지는 못한다는 점을 변환 형식을 통해서 명시적으로 표현하는 것. 
>
> 오류 처리 전략을 호출자에게 미루는 것으로 생각 해도 된다. 

```scala	
sealed trait Option[+A]
case class Some[+A](get: A) extends Option[A]
case object None extends Option[Nothing]
```







